#!/bin/sh

main() {
  if [ $# -gt 0 ]; then
    echo 'Arguments found, so executing them.'
    exec "$@"
  fi

  echo 'No arguments found, so executing kcl.'
  echo
  echo 'To customize KCL execution, set KCL_EXTRA_ARGS'
  echo 'and/or KCL_PROPERTIES_FILE in the environment.'

  ##
  # expand $KCL_EXTRA_ARGS so that users can inject extra arguments easily.
  # expand $KCL_PROPERTIES_FILE with sample.properties from kclpy as the default.
  exec java -cp "$(amazon_kclpy_helper.py --sample --print_classpath)" \
            $KCL_EXTRA_ARGS \
            com.amazonaws.services.kinesis.multilang.MultiLangDaemon \
            "${KCL_PROPERTIES_FILE:-sample.properties}"
}

main "$@"
