#!/bin/bash

export AWS_DEFAULT_REGION=us-east-1
export AWS_NO_VERIFY_SSL=1

echo 'Setting up localstack Kinesis for demo'

echo
echo 'Installing awscli to help set up the demo'
pip install -q awscli

shard_count=$(( 1 + (RANDOM % 6) ))

echo "Creating a stream named 'words' with a shard count of $shard_count."

aws --no-verify-ssl kinesis create-stream --stream-name words --shard-count "$shard_count"
aws --no-verify-ssl kinesis describe-stream --stream-name words

echo 'Adding some random words to the stream.'
aws --no-verify-ssl kinesis put-record --stream-name words --partition-key "$RANDOM" --data foo
aws --no-verify-ssl kinesis put-record --stream-name words --partition-key "$RANDOM" --data bar
aws --no-verify-ssl kinesis put-record --stream-name words --partition-key "$RANDOM" --data baz
aws --no-verify-ssl kinesis put-record --stream-name words --partition-key "$RANDOM" --data xyzzy
aws --no-verify-ssl kinesis put-record --stream-name words --partition-key "$RANDOM" --data xyzzy
aws --no-verify-ssl kinesis put-record --stream-name words --partition-key "$RANDOM" --data zik

echo
echo
echo
echo
echo

echo 'Starting Demo'
exec kcl
